sonar.organization=fabianportillo1996
sonar.projectKey=FabianPortillo1996_universe-monorepo

sonar.sources=apps/,packages/

sonar.exclusions=\
  **/node_modules/**,\
  **/coverage/**,\
  **/dist/**,\
  **/storybook-static/**,\
  **/.storybook/**,\
  **/*.config.ts,\
  **/*.config.js,\
  **/*.config.mjs,\
  **/*.d.ts

sonar.coverage.exclusions=\
  **/__tests__/**,\
  **/vitest.setup.*,\
  **/*.stories.tsx

sonar.javascript.lcov.reportPaths=apps/docs-web/coverage/lcov.info

sonar.inclusions=**/*.ts,**/*.tsx

sonar.qualitygate.wait=true
